version: 0.2

phases:
  pre_build:
    commands:
      - echo "ECR 로그인"
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.ap-southeast-2.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "이미지 태그 $IMAGE_TAG"

  build:
    commands:
      - echo "Docker 이미지 빌드 (Gradle 빌드 포함)"
      - docker build -t 416225317325.dkr.ecr.ap-southeast-2.amazonaws.com/lms-be:$IMAGE_TAG .

  post_build:
    commands:
      - echo "ECR로 푸시"
      - docker push 416225317325.dkr.ecr.ap-southeast-2.amazonaws.com/lms-be:$IMAGE_TAG
      - echo "빌드 완료 - 이미지 태그 $IMAGE_TAG"

artifacts:
  base-directory: yaml_folder
  files:
    - 00-namespace.yaml
    - backend-configmap.yaml
    - backend-deployment.yaml
    - backend-service.yaml
    - db-configmap.yaml
    - db-secret.yaml
    - db-service.yaml
    - db-statefulset.yaml
